docker:
  rules:
    - if: '$CI_COMMIT_TAG'
  image: docker:latest
  services:
    - docker:dind
  variables:
    CONTAINER_RELEASE_IMAGE: ${CI_REGISTRY_IMAGE}:latest
    CONTAINER_TAG_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
  script:
    - echo "${CI_REGISTRY_PASSWORD}" | docker login -u ${CI_REGISTRY_USER} --password-stdin ${CI_REGISTRY}
    - docker build --pull -t ${CONTAINER_RELEASE_IMAGE} .
    - docker image tag ${CONTAINER_RELEASE_IMAGE} ${CONTAINER_TAG_IMAGE}
    - docker push ${CONTAINER_RELEASE_IMAGE}
    - docker push ${CONTAINER_TAG_IMAGE}
